### ISSUE TITLE
“Error”: “contact: failed to dial storage node

### ISSUE THREAD

**Issue by ZaineJJ** [dappnode/DAppNodePackage-storj#40]
UDP port 28967:28967 has to be open too 

https://forum.storj.io/t/i-am-getting-error-contact-failed-to-dial-storage-node/18016
Went to their forum and found the fix 

Need to implement a default UDP port opening too. 
Hope future users doesn't encounter this issue.

**Comment by tropicar** [comment]
By default in this package, the port 28967 is already exposed, UDP and TCP.
```
    ports:
      - "28967:28967"
```
But iI think we should inform the user needs to open the ports in the router to make works this package.
When did you opened the port in your router fixe the error?

**Comment by ZaineJJ** [comment]
Router did Portforwarding properly 
By default the storj application only shows TCP enabled, I've added UDP manually and the error goes away.
![B4A5EF78-43F6-40CA-AFE5-17D651A1730A](https://user-images.githubusercontent.com/88610565/162415111-1f3a695b-47d0-4463-882f-23181a12284b.png)
