### ISSUE TITLE
Restarting since update to 0.0.15

### ISSUE THREAD

**Issue by benv666** [dappnode/DAppNodePackage-storj#43]
Storj won't start anymore after this update (installed 0.0.14 literally yesterday), keeps restarting.
![image](https://user-images.githubusercontent.com/165034/163010540-13b620a8-e8dd-4b9f-93f1-d08bdbdcbc56.png)

Logs show the entrypoint is nowhere to be found:
```
/usr/bin/entrypoint.sh: line 49: /app/storagenode: No such file or directory
```
(repeating)

**To Reproduce**

1. Install version 0.0.15 as an upgrade from 0.0.14, just next next next without changes.

**Expected behavior**

Functional Storj

**Screenshots**

See above

**DAppNode version:**

- Package  0.0.15 (v1.52.2 upstream)
- OS: DAppNode Xtreme

**Additional context**

**Comment by tropicar** [comment]
Firstly, thank you for the feedback. We advised via Discord, we recommend using the previous version until we update to the next version where we will fix this issue. This was the patch https://github.com/dappnode/DAppNodePackage-storj/commit/7358004cb8ffb3ab781311ea7a95e9838c82da45. If you want to install the previous version  you can do it http://my.dappnode/#/installer/%2Fipfs%2FQmWjwCEBuwiRKTmov4TYuQKSdzM14vv4nrLwyj9g5QPtmA , you need to enable the bypass only signed safe restricction

**Comment by tropicar** [comment]
Fixed 2 previous versions. It was a problem related to some changes they did to the location of some files in the image of the container.
Now we download the binaries directly in a proper path.
